---
- name: Add LDAP Computers 
  hosts: localhost
  connection: local
  gather_facts: false
  become: false

  vars:
    ldap_server: "ldap://localhost:389"
    admin_dn: "cn=admin,dc=example,dc=com"
    admin_pw: "."
    base_dn: "dc=example,dc=com"
    var_default_shell: "/bin/bash"
    var_default_home_path: "/home"
    var_min_password_length: 15
    var_min_password_age: 1
    var_password_warn_age: 14
    var_inactive_days: 35
    var_account_expire_days: -1
    var_max_password_age: 60
    var_default_password: "."
    var_approved_users: []

  vars_files:
    - vars.yaml
    - vault.yaml

  tasks:
    - name: "Adding computer {{ item.computer }}"
      loop: "{{ var_approved_computers }}"
      community.general.ldap_entry:
        dn: "cn={{ item.computer }},ou=computers,{{ base_dn }}"
        objectClass:
          - top
          - device
          - strongAuthenticationUser
        attributes:
          cn: "{{ item.computer }}"
          userCertificate: "{{ item.cert }}"
        state: present
        server_uri: "{{ ldap_server }}"
        bind_dn: "{{ admin_dn }}"
        bind_pw: "{{ admin_pw }}"
        binary_attributes:
          - userCertificate
      no_log: true