---
- name: Setting up ldap servers
  hosts: ldap_servers
  become: true
  gather_facts: false
  vars_files:
    - vars.yaml
    - vault.yaml
  tasks:
    - ansible.builtin.include_tasks: bootstrap-ldap/add-service-accounts.yaml

  handlers:
    - name: Cleanup tmp
      ansible.builtin.file:
        path: "{{ remote_tmpdir }}"
        state: absent